"""Extract delivery notices from supplier e-mails with an LLM (LiteLLM) and validate them (Pydantic).

Replay mode (the default without ANTHROPIC_API_KEY) uses the recorded responses in recorded/.
"""

import json
import os
import sys
from pathlib import Path

os.environ.setdefault("LITELLM_LOCAL_MODEL_COST_MAP", "True")

import litellm  # noqa: E402
from pydantic import ValidationError  # noqa: E402
from rapidfuzz import fuzz, process  # noqa: E402

import inventory_data as d  # noqa: E402
from schema import DeliveryNotice  # noqa: E402

MODEL = os.environ.get("LLM_MODEL", "anthropic/claude-opus-5")
REPLAY = "--live" not in sys.argv and (
    "--replay" in sys.argv or not os.environ.get("ANTHROPIC_API_KEY"))
CATALOG = d.products().name.tolist()
SYSTEM = ("Extract the delivery notice from the supplier e-mail. Use the product names of the "
          "supermarket catalog: " + ", ".join(CATALOG))


def ask(messages: list[dict], response_format, recorded: Path | None) -> str:
    kwargs = {"mock_response": recorded.read_text()} if REPLAY and recorded else {}
    response = litellm.completion(model=MODEL, messages=messages, max_tokens=4000,
                                  response_format=response_format, **kwargs)
    return response.choices[0].message.content


def extract(email: Path) -> tuple[str, DeliveryNotice | None, str]:
    messages = [{"role": "system", "content": SYSTEM},
                {"role": "user", "content": email.read_text()}]
    answer = ask(messages, DeliveryNotice, Path("recorded") / f"{email.stem}.json")
    for attempt in (1, 2):
        try:
            return "ok" if attempt == 1 else "ok after retry", \
                DeliveryNotice.model_validate_json(answer), ""
        except ValidationError as e:
            problems = "; ".join(f"{'.'.join(map(str, x['loc']))}: {x['msg']}" for x in e.errors())
            if attempt == 2:
                return "quarantined", None, problems
            print(f"    invalid answer ({problems[:90]}) -> retry with the errors")
            messages += [{"role": "assistant", "content": answer},
                         {"role": "user", "content": f"Your answer is not valid: {problems}. "
                          "Return a corrected JSON object."}]
            retry = Path("recorded") / f"{email.stem}.retry.json"
            answer = ask(messages, DeliveryNotice, retry if retry.exists() else None)
    raise AssertionError("unreachable")


def unknown_products(notice: DeliveryNotice) -> list[str]:
    return [i.product for i in notice.items
            if process.extractOne(i.product, CATALOG, scorer=fuzz.ratio)[1] < 90]


print(f"Model: {MODEL} ({'replay of recorded responses' if REPLAY else 'live'})\n")
print("Variant 1 (first slide): a hand-written JSON schema as response_format")
schema = {"type": "json_schema", "json_schema": {
    "name": "delivery_notice", "strict": True, "schema": DeliveryNotice.model_json_schema()}}
first = Path("emails/01_fresh_fields.txt")
text = ask([{"role": "system", "content": SYSTEM}, {"role": "user", "content": first.read_text()}],
           schema, Path("recorded/01_fresh_fields.json"))
print(f"  {first.name}: {json.loads(text)['items'][0]}")
print("  (the schema dict is generated by DeliveryNotice.model_json_schema(), see schema.json)\n")
Path("schema.json").write_text(json.dumps(DeliveryNotice.model_json_schema(), indent=2) + "\n")

print("Variant 2 (second slide): response_format=DeliveryNotice, then validate and retry\n")
quarantine = []
for email in sorted(Path("emails").glob("*.txt")):
    print(f"  {email.name}")
    status, notice, problems = extract(email)
    if notice and (unknown := unknown_products(notice)):
        status, problems = "quarantined", f"products not in the catalog: {unknown}"
    print(f"    -> {status}" + (f": {problems}" if problems else
                                f": {len(notice.items)} items for {notice.delivery_date}"))
    if status == "quarantined":
        quarantine.append({"email": email.name, "problems": problems})

Path("out").mkdir(exist_ok=True)
Path("out/quarantine.json").write_text(json.dumps(quarantine, indent=2))
print(f"\n{len(quarantine)} e-mail(s) in out/quarantine.json for a human to handle")
