"""Write the generated statistics into DATACARD.md (between the two marker lines)."""

import re
from pathlib import Path

import pandas as pd

import inventory_data as d

START, END = "<!-- generated: start -->", "<!-- generated: end -->"


def md(df: pd.DataFrame, **kw) -> str:
    return df.to_markdown(**kw)


def stats() -> str:
    sales, products, stores = d.sales(), d.products(), d.stores()
    tables = {"products": products, "suppliers": d.suppliers(), "stores": stores, "sales": sales,
              "deliveries": d.deliveries(), "stock_counts": d.stock_counts(),
              "weather": d.weather(), "oos_reports": d.oos_reports()}
    sizes = pd.DataFrame({"rows": {k: len(v) for k, v in tables.items()},
                          "columns": {k: v.shape[1] for k, v in tables.items()}})

    s = sales.merge(products[["id", "category", "unit"]], left_on="product_id", right_on="id")
    by_cat = s.groupby("category").agg(products=("product_id", "nunique"),
                                       revenue=("revenue", "sum"))
    by_cat["share of revenue"] = (by_cat.revenue / by_cat.revenue.sum()).map("{:.1%}".format)
    by_cat = by_cat.drop(columns="revenue").sort_values("products", ascending=False)

    per_day = s.groupby(["unit"]).quantity.describe(percentiles=[0.1, 0.5, 0.9])[
        ["mean", "10%", "50%", "90%", "max"]].round(1)
    zero_stock = (d.inventory().on_hand_system <= 0).mean()
    promo = sales.promo.mean()
    issues = d.errors().groupby(["table", "error_type"]).size().rename("count").reset_index()
    return "\n\n".join([
        f"Generated by `datacard_stats.py` from the cached data "
        f"({sales.date.min().date()} to {sales.date.max().date()}).",
        "**Tables**\n\n" + md(sizes),
        "**Products and revenue by category**\n\n" + md(by_cat),
        "**Sales per store, product, and day (by unit)**\n\n" + md(per_day),
        f"**Other facts**: {promo:.1%} of the product-days are on promotion; on {zero_stock:.1%} "
        f"of the store-product-days the system stock is zero at the end of the day (the "
        f"recorded sales of these days are censored).",
        "**Injected data quality problems in the dirty tables** (`errors()`)\n\n"
        + md(issues, index=False),
    ])


path = Path("DATACARD.md")
text = path.read_text()
new = re.sub(f"{START}.*{END}", f"{START}\n{stats()}\n{END}", text, flags=re.S)
path.write_text(new)
print(f"Updated the statistics in {path} ({len(new.splitlines())} lines)")
